<a href="https://colab.research.google.com/github/HarikaSatti06112001/Deep_Learning/blob/main/advanced_tensorflow_primitives_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Scalar-Vector multiplication
import torch
import tensorflow as tf
import numpy as np

# PyTorch
x = torch.tensor([1, 2, 3])
y = 2
result = y * x
print(result)

# TensorFlow
x = tf.constant([1, 2, 3])
y = 2
result = tf.multiply(y, x)
print(result)

# NumPy
x = np.array([1, 2, 3])
y = 2
result = y * x
print(result)


tensor([2, 4, 6])
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
[2 4 6]


Vector-Vector multiplication

In [2]:
# PyTorch
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
result = x * y
print(result)

# TensorFlow
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])
result = tf.multiply(x, y)
print(result)

# NumPy
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
result = x * y
print(result)


tensor([ 4, 10, 18])
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
[ 4 10 18]


Outer product

In [5]:
# Create two 1D tensors
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

# Reshape the tensors into 2D shape
a_2d = tf.reshape(a, (3, 1))
b_2d = tf.reshape(b, (1, 3))

# Compute the outer product of a and b
outer_prod = tf.matmul(a_2d, b_2d)

print(outer_prod)



tf.Tensor(
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]], shape=(3, 3), dtype=int32)


Scalar dot product

In [6]:

# PyTorch
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
result = torch.dot(x, y)
print(result)

# TensorFlow
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])
result = tf.tensordot(x, y, axes=1)
print(result)

# NumPy
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
result = np.dot(x, y)
print(result)

tensor(32)
tf.Tensor(32, shape=(), dtype=int32)
32


Hadamard product


In [7]:

# PyTorch
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
result = x * y
print(result)

# TensorFlow
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])
result = tf.multiply(x, y)
print(result)

# NumPy
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
result = np.multiply(x, y)
print(result)


tensor([ 4, 10, 18])
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
[ 4 10 18]


Batch matrix multiplication


In [8]:

# PyTorch
x = torch.rand


TENSOR CONTRACTION


In [9]:
a = torch.randn(2,3,5,7)
b = torch.randn(11,13,3,17,5)
torch.einsum('pqrs,tuqvr->pstuv', [a, b]).shape

torch.Size([2, 7, 11, 13, 17])

In [10]:
#BILINEAR TRANSFORMATION
a = torch.randn(2,3)
b = torch.randn(5,3,7)
c = torch.randn(2,7)
torch.einsum('ik,jkl,il->ij', [a, b, c])

tensor([[-0.0310, -5.4643, -5.8462,  5.4654, -2.5742],
        [-1.4028,  0.3174, -2.9896,  3.5333,  6.1320]])

In [11]:
import torch.nn.functional as F

def random_tensors(shape, num=1, requires_grad=False):
  tensors = [torch.randn(shape, requires_grad=requires_grad) for i in range(0, num)]
  return tensors[0] if num == 1 else tensors

# Parameters
# -- [num_actions x hidden_dimension]
b = random_tensors([5, 3], requires_grad=True)
# -- [num_actions x hidden_dimension x hidden_dimension]
W = random_tensors([5, 3, 3], requires_grad=True)

def transition(zl):
  # -- [batch_size x num_actions x hidden_dimension]
  return zl.unsqueeze(1) + F.tanh(torch.einsum("bk,aki->bai", [zl, W]) + b)

# Sampled dummy inputs
# -- [batch_size x hidden_dimension]
zl = random_tensors([2, 3])

transition(zl)

/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py:1956: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")


tensor([[[-2.0845,  0.1996,  1.3517],
         [-1.5947,  0.6471,  1.4966],
         [-0.0954,  1.1319,  0.1072],
         [-0.6178,  0.4256,  1.2624],
         [-2.0508, -0.0833,  1.3276]],

        [[-0.2545,  1.2938, -0.9347],
         [-0.9028,  2.6235,  0.3607],
         [ 0.6876,  2.5235,  0.8626],
         [ 0.7556,  0.8940,  0.8621],
         [-1.2245,  0.6520,  0.8421]]], grad_fn=<AddBackward0>)

ATTENTION

In [12]:
bM, br, w = random_tensors([7], num=3, requires_grad=True)
# -- [hidden_dimension x hidden_dimension]
WY, Wh, Wr, Wt = random_tensors([7, 7], num=4, requires_grad=True)

# Single application of attention mechanism 
def attention(Y, ht, rt1):
  # -- [batch_size x hidden_dimension] 
  tmp = torch.einsum("ik,kl->il", [ht, Wh]) + torch.einsum("ik,kl->il", [rt1, Wr])
  Mt = F.tanh(torch.einsum("ijk,kl->ijl", [Y, WY]) + tmp.unsqueeze(1).expand_as(Y) + bM)
  # -- [batch_size x sequence_length]
  at = F.softmax(torch.einsum("ijk,k->ij", [Mt, w])) 
  # -- [batch_size x hidden_dimension]
  rt = torch.einsum("ijk,ij->ik", [Y, at]) + F.tanh(torch.einsum("ij,jk->ik", [rt1, Wt]) + br)
  # -- [batch_size x hidden_dimension], [batch_size x sequence_dimension]
  return rt, at

# Sampled dummy inputs
# -- [batch_size x sequence_length x hidden_dimension]
Y = random_tensors([3, 5, 7])
# -- [batch_size x hidden_dimension]
ht, rt1 = random_tensors([3, 7], num=2)

rt, at = attention(Y, ht, rt1)
at  # -- print attention weights


<ipython-input-12-f7e5857da595>:11: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  at = F.softmax(torch.einsum("ijk,k->ij", [Mt, w]))


tensor([[0.2195, 0.0891, 0.3087, 0.2711, 0.1116],
        [0.1431, 0.2479, 0.1838, 0.2142, 0.2110],
        [0.1140, 0.4318, 0.1593, 0.1182, 0.1768]], grad_fn=<SoftmaxBackward0>)